aws-observability/terraform-aws-observability-accelerator

modules/add-ons/adot-operator/main.tf
Pin eks-blueprint cert-manager version. This fixes an issue for an upstream requirement
=> Pin cert-manager module version

examples/existing-cluster-with-base-and-infra/README.md, examples/existing-cluster-with-base-and-infra/terraform.tfvars
Simplified approach for solving #31 - Uses Amazon managed Grafana control plane API  for short lived API keys instead of adding a dependency to a new service
=> Use short-lived Grafana API keys

modules/workloads/nginx/otel-config/templates/opentelemetrycollector.yaml
Changes the nginx module otel logging level to 'info' from 'debug'
Debug would provide too verbose logging.
- [ X ] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
=> Updating nginx otel log level

README.md, examples/existing-cluster-with-base-and-infra/README.md, examples/existing-cluster-with-base-and-infra/outputs.tf, locals.tf, outputs.tf
- Update Managed Grafana instructions for infrastructure monitoring example
- Add output for grafana workspace id `managed_grafana_workspace_id`
- Updates docs
Linked to #47
=> doc: Update Managed Grafana instructions

.github/workflows/plan-examples.yml
This PR updates the usage of set-output command in GH actions.
Reference : https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Volunteer
=> Update the usage of set-output command in GH actions

examples/eks-cluster-with-vpc/main.tf
Updating the Cluster's Kubernetes version and the instance types for the managed node group.
When deploying the EKS cluster i found that the add-ons would fail and the first thing i would need to do is upgrade the cluster's version. 
Upgrading the instance type as a best practice. 
- [N/A] Yes, I have added a new example under [examples](https://github.com/aws-observability/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [N/A] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
=> Update kuberenetes and instance type

examples/eks-cluster-with-vpc/main.tf
T4 instances are not generally available, with [this issue](https://github.com/aws-observability/terraform-aws-observability-accelerator/issues/89) we'll provide customization options
=> fix: EKS cluster with VPC revert to t3 instances

docs/helpers/new-eks-cluster.md, examples/eks-cluster-with-vpc/main.tf, examples/eks-cluster-with-vpc/variables.tf
See #89.
Added a variable to change the default instance type for the EKS Cluster
Adds a parameter to the example to override the default instance type for the EKS Cluster.
On some regions / scenarios lack of availability of the default instance type will make the deployment of the example fail. This PR allows to easily change to an available instance in the environment.
- [N/A] Yes, I have added a new example under [examples](https://github.com/aws-observability/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [N/A] Yes, I have created another PR for add-ons under …
=> Added parameter for instance type

.pre-commit-config.yaml
The goal of this PR is to resolve #92 by updating and freezing the pre-commit hook `rev` to git sha via: 
**--freeze: new in 1.21.0: Store "frozen" hashes in [rev](https://pre-commit.com/#repos-rev) instead of tag names**
Ensure validation/dependency chain is unaltered.
=> Update and freeze pre-commit hook versions

.github/workflows/pre-commit.yaml, .pre-commit-config.yaml, .tflint.hcl
The goal of this PR is to fix #96 by updating the TFLint AWS rules plugin to `0.21.1` and fixing the pre-commit args uses to source from the .tflint.hcl file residing in this repository.
Ensure we're using updated rules and the config file is no longer superfluous.
=> Update tflint aws plugin and fix pre-commit to use config file

.github/PULL_REQUEST_TEMPLATE.md, README.md
This PR resolves #94 by updating the README.md link pointing to the LICENSE file and the PR workflow template pointing at the eks blueprint.
Ensure documentation is relevant and reflects/supports the project.
=> Update readme and pr template to point to o11y accel repo

docs/workloads/managed-prometheus.md
Adds teardown instructions for managed prometheus workload module.
This one was missing teardown instructions.
=> amp workload teardown

docs/helpers/new-eks-cluster.md, examples/eks-cluster-with-vpc/README.md, examples/existing-cluster-nginx/README.md
Fix reference link on example docs.  (#120)
Broken reference links not pointing to a valid address. (_broken link_)
=> doc: eks cluster with vpc ref tag

docs/helpers/managed-grafana.md
Add "terraform-aws-observability-accelerator" to the path
The folder path is wrong and did not include "terraform-aws-observability-accelerator"
- [x ] Yes, I have updated the [Pages](https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/docs) for this feature
=> Fix folder path

README.md, examples/existing-cluster-java/README.md, examples/existing-cluster-java/main.tf, examples/existing-cluster-java/variables.tf, examples/existing-cluster-nginx/README.md, examples/existing-cluster-nginx/main.tf, examples/existing-cluster-nginx/variables.tf, examples/existing-cluster-with-base-and-infra/README.md, examples/existing-cluster-with-base-and-infra/main.tf, examples/existing-cluster-with-base-and-infra/variables.tf, outputs.tf, variables.tf
Control the publish of dashboard files only if the folder is created by the observability accelerator 
A bug https://github.com/aws-observability/terraform-aws-observability-accelerator/issues/147
None
=> Publish dashboards only if grafana folder exists

examples/existing-cluster-with-base-and-infra/README.md, examples/existing-cluster-with-base-and-infra/terraform.tfvars, examples/existing-cluster-with-base-and-infra/variables.tf
This change removes `terraform.tfvars` from `examples/existing-cluster-with-base-and-infra`, and uses `variables.tf` for any defaults.
When [following the instructions HERE](https://aws-observability.github.io/terraform-aws-observability-accelerator/eks/) it directs the reader to set `TF_VAR_xxxx` environment variables. However, since there is already `terraform.tfvars`, the tfvars file will [take precedent over environment variables per the terraform docs](https://developer.hashicorp.com/terraform/language/values/variables#variable-definition-precedence). This results in `aws_region`, `eks_cluster_id`, and `managed_prometheus_workspace_id` being unable to be set. 
Alternatively, we could change the directions on the site. Open to …
=> Remove terraform.tfvars from example

mkdocs.yml
Adds Docs for multicluster example
=> adding multicluster docs

modules/eks-monitoring/add-ons/aws-for-fluentbit/data.tf, modules/eks-monitoring/add-ons/aws-for-fluentbit/values.yaml
Fix for https://github.com/aws-observability/terraform-aws-observability-accelerator/issues/158
This will apply retention automatically on new log groups
=> Fix setup logs retention policy

modules/eks-monitoring/otel-config/templates/opentelemetrycollector.yaml
Support OTLP receiver for custom metrics
Only prometheus metrics are being collected from custom applications. This adds an otlp receiver for metrics into Managed Service for Prometheus
=> Add OTLP receiver for custom metrics

README.md, docs/concepts.md, examples/eks-cluster-with-vpc/versions.tf, examples/eks-multicluster/main.tf, examples/eks-multicluster/providers.tf, examples/eks-multicluster/variables.tf, examples/eks-multicluster/versions.tf, examples/existing-cluster-java/README.md, examples/existing-cluster-java/main.tf, examples/existing-cluster-java/variables.tf, examples/existing-cluster-java/versions.tf, examples/existing-cluster-nginx/README.md, examples/existing-cluster-nginx/main.tf, examples/existing-cluster-nginx/variables.tf, examples/existing-cluster-nginx/versions.tf, examples/existing-cluster-with-base-and-infra/README.md, examples/existing-cluster-with-base-and-infra/main.tf, examples/existing-cluster-with-base-and-infra/versions.tf, examples/managed-prometheus-monitoring/versions.tf, main.tf, modules/eks-monitoring/README.md, modules/eks-monitoring/patterns/java/README.md, modules/eks-monitoring/patterns/java/versions.tf, modules/eks-monitoring/patterns/nginx/README.md, modules/eks-monitoring/patterns/nginx/versions.tf, modules/eks-monitoring/versions.tf, variables.tf, versions.tf
Cleaning Grafana provider following up on https://github.com/aws-observability/terraform-aws-observability-accelerator/pull/175
=> Remove Grafana provider for EKS

modules/eks-monitoring/add-ons/aws-for-fluentbit/README.md, modules/eks-monitoring/add-ons/aws-for-fluentbit/locals.tf, modules/eks-monitoring/add-ons/aws-for-fluentbit/values.yaml, modules/eks-monitoring/add-ons/aws-for-fluentbit/variables.tf
Cleans up log format for logs collected by FluentBit
Before:
```json
{
"log": "2023-06-23T12:25:48.21020769Z stderr F 2023-06-23T12:25:48.210Z\tinfo\tMetricsExporter\t{\"kind\": \"exporter\", \"data_type\": \"metrics\", \"name\": \"logging\", \"resource metrics\": 1, \"metrics\": 336, \"data points\": 866}",
"kubernetes": {
"pod_name": "adot-collector-67ddcff9d8-phwpj",
"namespace_name": "adot-collector-kubeprometheus",
"pod_id": "a6265b55-e0f1-446d-94a3-36fe02c2d05f",
"labels": {
"app.kubernetes.io/component": "opentelemetry-collector",
"app.kubernetes.io/instance": "adot-collector-kubeprometheus.adot",
"app.kubernetes.io/managed-by": "opentelemetry-operator",
"app.kubernetes.io/name": "adot-collector",
"app.kubernetes.io/part-of": "opentelemetry",
"app.kubernetes.io/version": "latest", …
```
=> Fluentbit improvements 

docs/eks/index.md, modules/eks-monitoring/README.md, modules/eks-monitoring/main.tf, modules/eks-monitoring/otel-config/Chart.yaml, modules/eks-monitoring/otel-config/templates/opentelemetrycollector.yaml, modules/eks-monitoring/otel-config/values.yaml, modules/eks-monitoring/variables.tf
As explained here #196 , the aim is to give you the option of adding more customised metrics configurations.
=> Extend configuration for customMetrics

modules/eks-monitoring/dashboards.tf
Currently Flux is using the tag with the branch naming, and this PR should fix
=> Use tags for flux repository

docs/adothealth/index.md, docs/container-insights/eks.md, docs/eks/eks-apiserver.md
Some of the docs assets live under contributors' forks. This PR move them to upstream
=> chore: Cleanup docs assets

docs/eks/nginx.md, examples/existing-cluster-nginx/README.md, examples/existing-cluster-nginx/sample_traffic/nginix-traffic-sample.yaml
Adds sample NGINX traffic generator deployment to the repository.
Fix #231
The current [file](https://github.com/aws-samples/amazon-cloudwatch-container-insights/blob/main/k8s-deployment-manifest-templates/deployment-mode/service/cwagent-prometheus/sample_traffic/nginx-traffic/nginx-traffic-sample.yaml) used for the examples uses a deprecated API, adding the example file in the repository will allow this deployment to succeed.
- [N/A ] Yes, I have added a new example under [examples](https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/examples) to support my …
=> Added updated example for traffic generator

.github/workflows/plan-examples.py
As we don't have a cross account setup for tests, this skips the x account example and fix the test badge
=> CI: Skip cross account testing

examples/eks-cluster-with-vpc/versions.tf, examples/eks-container-insights/README.md, examples/eks-container-insights/versions.tf, examples/eks-cross-account-with-central-amp/versions.tf, examples/eks-istio/README.md, examples/eks-istio/versions.tf, examples/eks-multicluster/versions.tf, examples/existing-cluster-java/README.md, examples/existing-cluster-java/versions.tf, examples/existing-cluster-nginx/README.md, examples/existing-cluster-nginx/versions.tf, examples/existing-cluster-with-base-and-infra/README.md, examples/existing-cluster-with-base-and-infra/versions.tf, modules/eks-container-insights/README.md, modules/eks-container-insights/versions.tf, modules/eks-monitoring/README.md, modules/eks-monitoring/add-ons/external-secrets/README.md, modules/eks-monitoring/add-ons/external-secrets/versions.tf, modules/eks-monitoring/patterns/istio/README.md, modules/eks-monitoring/patterns/istio/versions.tf, modules/eks-monitoring/patterns/java/README.md, modules/eks-monitoring/patterns/java/versions.tf, modules/eks-monitoring/patterns/nginx/README.md, modules/eks-monitoring/patterns/nginx/versions.tf, modules/eks-monitoring/versions.tf
Fix issue with gavinbunney/kubectl on eks 1.28. Some resource disappear or re-created on every tf apply
Migrate to alekc/kubectl providers
close #244 
Make it work on every tf apply with eks 1.28
=> fix: eks 1.28 migrate kubectl provider to alekc repo

examples/eks-cluster-with-vpc/variables.tf
Default cluster creation to 1.28. We recently merged a PR to validate 1.28 https://github.com/aws-observability/terraform-aws-observability-accelerator/pull/245
=> chore: Bump to EKS 1.28

docs/ecs/ecs-monitoring-on-ec2.md
=> Fix Issues with the ECS Doc

docs/eks/index.md
Update docs for Grafana v10 changes
=> Update docs for Service accounts and Grafana v10

docs/container-insights/eks.md
Updates documentation for Application Signals
=> Instructions updates for App Signals GA

modules/eks-monitoring/dashboards.tf, modules/eks-monitoring/patterns/istio/main.tf, modules/eks-monitoring/patterns/java/main.tf, modules/eks-monitoring/patterns/nginx/main.tf
#229  Updated the flux system kustomization API version on the new versions from v1beta2 to v1 to resolve dashboard issues on EKS 1.27+
=> Issue#229 changing v1beta2 to v1 for flux

.github/workflows/plan-examples.yml, modules/eks-monitoring/otel-config/templates/opentelemetrycollector.yaml
newer versions of ADOT forces interpolation changes from `$var` to `${var}`. Current installations are broken with such messages
```
{"level":"ERROR","timestamp":"2024-09-16T12:28:10Z","logger":"conversion-webhook","message":"failed to convert","requ │
│ est":"25310353-c5f2-408d-a0f7-3425e18ab95c","error":"failed to convert to v1beta1: could not convert config json to v │
│ 1beta1.Config","stacktrace":"[sigs.k8s.io/controller-runtime/pkg/webhook/conversion.(*webhook).ServeHTTP](http://sigs.k8s.io/controller-runtime/pkg/webhook/conversion.(*webhook).ServeHTTP)\n\t/home/runn │
│ er/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/webhook/conversion/conversion.go:74\[nsigs.k8s.io/controller-](http://nsigs.k8s.io/controller-) │
│ …
```
=> (bugfix): Adot interpolation updates
