- examples/existing-cluster-nginx/README.md
- examples/existing-cluster-nginx/outputs.tf
- examples/existing-cluster-with-base-and-infra/README.md
- examples/existing-cluster-with-base-and-infra/outputs.tf
- modules/workloads/infra/README.md
- modules/workloads/infra/outputs.tf
- modules/workloads/nginx/README.md
- modules/workloads/nginx/outputs.tf
Add dashboards link as outputs to modules and examples 
#40
> feat: Add dashboards output

- examples/existing-cluster-nginx/README.md
Provides a more detailed image of the NGINX dashboard example.
> Updating Screenshot for NGINX Example

- .github/workflows/plan-examples.py
- .github/workflows/plan-examples.yml
- .github/workflows/pre-commit.yaml
- .github/workflows/stale_issue_pr.yaml
- TF Plan example Github Workflow
- Pre-commit updates from upstream
> Plan examples workflow

- .pre-commit-config.yaml
- README.md
- examples/eks-cluster-with-vpc/main.tf
- examples/eks-cluster-with-vpc/versions.tf
- examples/existing-cluster-java/README.md
- examples/existing-cluster-java/versions.tf
- examples/existing-cluster-nginx/README.md
- examples/existing-cluster-nginx/versions.tf
- examples/existing-cluster-with-base-and-infra/README.md
- examples/existing-cluster-with-base-and-infra/versions.tf
- modules/add-ons/adot-operator/README.md
- modules/add-ons/adot-operator/main.tf
- modules/add-ons/adot-operator/variables.tf
- modules/add-ons/adot-operator/versions.tf
- modules/workloads/infra/README.md
- modules/workloads/infra/main.tf
- modules/workloads/infra/versions.tf
- modules/workloads/java/README.md
- modules/workloads/java/main.tf
- modules/workloads/java/versions.tf
- modules/workloads/nginx/README.md
- modules/workloads/nginx/main.tf
- modules/workloads/nginx/versions.tf
- versions.tf
Support latest Terraform version
#45
> Add support for tf 1.3+

- README.md
- modules/workloads/infra/dashboards/cluster.json
- modules/workloads/infra/dashboards/kubelet.json
- modules/workloads/infra/dashboards/namespace-workloads.json
- modules/workloads/infra/dashboards/nodeexporter-nodes.json
- modules/workloads/infra/dashboards/nodes.json
- modules/workloads/infra/dashboards/workloads.json
- Min query interval for dashboard panels. default from 15s to 1m
- Migrate panels versions
- Change lines overlays
> 💅🏾 Improvements: Infrastructure dashboards 

- .github/ISSUE_TEMPLATE/bug_report.yaml
- modules/add-ons/adot-operator/main.tf
Fixing https://github.com/aws-observability/terraform-aws-observability-accelerator/issues/70
> fix: eks permissions

- modules/add-ons/adot-operator/README.md
- modules/add-ons/adot-operator/variables.tf
Fixed a mistake in the description of the addon_config variable in the adot operator.
> fix: Fix a typo in a variable description

- modules/add-ons/adot-operator/README.md
- modules/add-ons/adot-operator/variables.tf
Fixed a mistake in the description of the helm_config variable in the adot operator.
> fix: variable description for cert manager

- .github/workflows/docbuild.yml
> docbuild workflow

- README.md
- docs/concepts.md
- docs/eks.md
- docs/helpers/new-eks-cluster.md
- docs/workloads/java.md
- docs/workloads/managed-prometheus.md
- docs/workloads/nginx.md
Update readmes with public doc references and dead links
> Public doc site references update

- .github/workflows/stale_issue_pr.yaml
> ci: Remove stale checks for feature requests

- docs/concepts.md
Updates broken link for min IAM permissions
> Update IAM link

- docs/helpers/new-eks-cluster.md
> typo: docs

- docs/eks/destroy.md
- docs/eks/index.md
- docs/index.md
- mkdocs.yml
Linked to https://github.com/aws-observability/terraform-aws-observability-accelerator/issues/101
Documentation update
> docs: custom metrics collection on EKS

- README.md
fixes merge conflict for https://github.com/aws-observability/terraform-aws-observability-accelerator/pull/108
> Fix merge conflicts

- README.md
- docs/concepts.md
Quick fix on documentation for missing closing quotes
> Fix missing closing quotes

- README.md
- docs/eks/destroy.md
- docs/eks/index.md
- docs/eks/java.md
- docs/eks/nginx.md
https://github.com/aws-observability/terraform-aws-observability-accelerator/pull/115 follow up
Points all links to main branch
> Update docs links

- docs/workloads/managed-prometheus.md
Adds documentation on the pre-req step for billing alarms (enabling billing metrics)
> doc: monitoring AMP, adding pre-req

- docs/eks/index.md
- docs/helpers/new-eks-cluster.md
- examples/existing-cluster-with-base-and-infra/terraform.tfvars
> Improve docs readability

- README.md
- docs/eks/index.md
- docs/eks/java.md
- docs/index.md
Keep docs relevant and up to date
> docs: improvements

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/stale_issue_pr.yaml
- Update PR templates
- Update stale issues and PRs inactivity period
> (chore): Issues and PRs CI updates

- modules/eks-monitoring/dashboards/cluster.json
- modules/eks-monitoring/dashboards/namespace-workloads.json
- modules/eks-monitoring/dashboards/workloads.json
Provides a fix for https://github.com/aws-observability/terraform-aws-observability-accelerator/issues/136
> Fix drill down links in dashboards

- docs/helpers/new-eks-cluster.md
- examples/eks-cluster-with-vpc/main.tf
- Updating modules version. This is necessary cause older versions are currently broken
- Fix numbers in the doc
> EKS cluster example updates

- docs/eks/multicluster.md
Corrects the formatting issues with the multicluster documentation
> Correcting the formatting issues in the markdown

- .github/workflows/plan-examples.yml
Supports e2e tests for  EKS multi cluster example
> Updated plan-examples.yml to support e2e tests for multi cluster example

- .github/workflows/plan-examples.yml
- .github/workflows/pre-commit.yaml
- examples/eks-multicluster/main.tf
Continuation of https://github.com/aws-observability/terraform-aws-observability-accelerator/pull/165
> Plan tests

- examples/managed-grafana-workspace/main.tf
- examples/managed-grafana-workspace/readme.md
- examples/managed-grafana-workspace/versions.tf
- mkdocs.yml
> Grafana v9.4

- docs/eks/index.md
- modules/eks-monitoring/add-ons/external-secrets/README.md
- modules/eks-monitoring/add-ons/external-secrets/main.tf
> Replacing Secrets Manager to SSM to store Grafana API Key

- modules/eks-monitoring/add-ons/external-secrets/main.tf
> Fixing SSM Parameter Issue

- docs/contributors.md
- docs/eks/index.md
- modules/eks-monitoring/README.md
- modules/eks-monitoring/add-ons/external-secrets/README.md
> Fixing Documentation issues with Secrets Manager

- docs/eks/index.md
- modules/eks-monitoring/README.md
- modules/eks-monitoring/versions.tf
Fixes the doc for custom metrics collection
> fix(doc): EKS custom metrics collection

- modules/eks-monitoring/alerts.tf
A long due #102 
Before 
After  (only watchdog alert)
> Cleans up alert rules

- docs/eks/istio.md
> Fixing broken link

- examples/eks-cluster-with-vpc/main.tf
- examples/eks-cluster-with-vpc/variables.tf
- examples/eks-istio/README.md
- examples/eks-istio/main.tf
> fix: EKS cluster example

- mkdocs.yml
Fixes doc pathing
Logo is missing from doc site.
> fixing logo

- docs/concepts.md
- docs/eks/tracing.md
Fixes typos and some markdown syntax in docs. 
To provide a better documentation for the community.
It just fixes some typos and syntaxes. No TF code was modified or features implemented.
> Fixes typos and markdown syntax in  the documentation

- modules/eks-monitoring/locals.tf
> Hotfix apiserver links

- modules/eks-monitoring/main.tf
fix an error I introduced in my previous commit.
See #202 & #196
> Fix customMetrics issue

- docs/adothealth/index.md
- mkdocs.yml
This PR is for adding the docs for ADOT collector monitoring.
Part of the virtual Hackathon on the [AWS Observability Accelerator](https://github.com/aws-observability/terraform-aws-observability-accelerator).
> Add docs for adothealth monitoring

- docs/adothealth/index.md
> Update ADOT collector monitoring docs

- modules/eks-monitoring/otel-config/templates/opentelemetrycollector.yaml
Following #265, misconfiguration on ADOT service telemetry logging config
> fix(eks-monitoring): ADOT logs key

- modules/eks-monitoring/otel-config/templates/opentelemetrycollector.yaml
#279  Resolved the api server replace issue for configmap on the adot config
> issue#279-fix apiserver enabling cm issue

- .github/workflows/markdown-link-check.yaml
Update CI tests with bumping node version
> (ci tests): Bump node version
